# Generated by Django 4.1.2 on 2022-10-25 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_inventory_stock_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
